export { default as parserHtml } from "@html-eslint/parser"
export { default as parserTs } from "@typescript-eslint/parser"
export { default as parserJsonc } from "jsonc-eslint-parser"
export { default as parserToml } from "toml-eslint-parser"
export { default as parserYaml } from "yaml-eslint-parser"
