export { default as parserTs } from '@typescript-eslint/parser'
export { default as parserAstro } from 'astro-eslint-parser'
export { default as parserJsonc } from 'jsonc-eslint-parser'
export { default as parserSvelte } from 'svelte-eslint-parser'
export { default as parserToml } from 'toml-eslint-parser'
export { default as parserVue } from 'vue-eslint-parser'
export { default as parserYaml } from 'yaml-eslint-parser'
